### PR TITLE
Add support for namespace-protected MEL procedure calls. Issue #359.

### PR DESCRIPTION
**Pull request by kartikg3**
Added support for namespace-protected MEL procedure calls using ```pymel.core.language.Mel``` class, by wrapping up the ```_call``` that was originally returned by ```Mel.__getattr__``` in the new class ```pymel.core.language.MelCallable```.

Also added test cases for ```pymel.core.language.Mel```, including tests for the above addition.

### CODE REVIEW

**Comment by kartikg3** [comment]
Thanks for your reply Paul. Are you refering to the _call function in the MelCallable and Mel classes? Or are you suggesting if we can move _call construction in MelCallable into MelCalable.__call__?

Do let me know, so I can get on that asap.

**Comment by kartikg3** [comment]
Hey Paul. I have refactored the classes based on your suggestions. They test out fine. Please let me know if you have any other suggestions. Thank you.

**Comment by elrond79** [comment]
Better - it addresses the duplicated code issue, but still leaves an unnecessary _call function - basically, in a function, you're then dynamically creating another function, then calling that function, returning it's result, and throwing away the dynamically created function.

Just went ahead and made the fix for that myself, though, and merged your changes in.  Thanks again for the contribution - especially appreciate the new tests!

**Comment by kartikg3** [comment]
Yes! How did I fail to see that. Note-to-self: avoid commits after 2 AM.

I will get that fixed.

**Comment by kartikg3** [comment]
Just realized that you have already made that fix. Thanks Paul.

**Pull request merged**
