### PR TITLE
Fix for Issue #343

### PR DESCRIPTION
**Pull request by kartikg3**
Modify getClassfication to support satisfies kwarg. Issue #343.

Please cherry-pick commit - 88dcb72
i.e. only cherry-pick these files:

pymel/core/general.py
pymel/core/nodetypes.py
tests/test_nodetypes.py

Thank you.

### CODE REVIEW

**Comment by kartikg3** [comment]
Hey guys,

Are there any issues keeping this pull request from being merged? Let me know and I will make the changes.

Thanks.

Regards,
Kartik

**Comment by kartikg3** [comment]
Hey guys,

Pinging on this again. Please let me kw if there is anything keeping you from merging this request, and I will make the changes.

**Comment by elrond79** [comment]
Just cherry-picked as requested and merged. In future, though, would be easier if you could create a pull request yourself, with only the changes you want merged.  This PR had a bunch of duplicate commits, which were already merged, and then a commit reverting some of these already-merged changes.  Was definitely a little confusing.
Regardless, though, appreciate the submission. Thanks!

**Comment by kartikg3** [comment]
Thanks Paul. I realized that with this pull request that was done a while ago. I had munged up some extra unnecessary commits in this branch that was hard to cleanup and roll back. 

As you can see, my other PRs have not been this way.

Thank you for merging!

**Pull request closed without merging**
